permalink:  /:title/

url: 'http://inspiring.online'
baseurl: '/'

# Title tag variables
title: Inspiring Online
tagline: 'Inspiring things, on the online landscape.'

# Links tag variables
twitter: "twholman"
github:  "tholman"

# Other external links
analytics_tracking_id: "UA-22825241-1"

# Misc variables
highlighter: 'rouge'
encoding: utf-8

# Number of posts on each page.
paginate: 10
paginate_path: "/:num/"
var_older: 'Next'
var_newer: 'Previous'

# External resources
gems: [jekyll-paginate]
