permalink:  /:title/

url: 'http://inspiring.online'
baseurl: '/'
remoteAssetUrl: https://s3.amazonaws.com/inspiring.online/

# Title tag variables
title: Inspiring Online
tagline: 'An open source blog for inspiring and creative online work!'

# Other external links
analytics_tracking_id: "UA-83557691-1"

# Misc variables
highlighter: 'rouge'
encoding: utf-8

# Number of posts on each page.
paginate: 20
paginate_path: "/:num/"
var_older: 'Next'
var_newer: 'Previous'

# External resources
gems: [jekyll-paginate]
